### ISSUE TITLE
Missing doc content

### ISSUE THREAD

**Issue by GreatZar** [ansible-lockdown/RHEL7-STIG#355]
In branch "legacy_devel_v0_2_0" the doc folder/dir has all of the documentation. For the current/default branch "devel", there is no documentation.

**Comment by georgenalen** [comment]
GreatZar,
 That is something we are looking at removing going forward. The idea is that we now have a Wiki dedicated to documenting the variables in the role as well as other wiki's to guide usage as well as the restructured README. With that I wanted to get some input from the community if the Wiki's can take place of the docs folder. Let me know if the doc creation element from the docs folder being replaced by the Wiki's causes you issues and what those issues are, then we can circle back our discussions on removing that element. 

George

**Comment by GreatZar** [comment]
For private networks, it's very handy to have some documentation local and downloaded with the rest of the content. Oh well...
