### ISSUE TITLE
Update to Version Tagging

### ISSUE THREAD

**Issue by georgenalen** [ansible-lockdown/RHEL7-STIG#356]
Hello,
 I wanted to give an update on a tagging change that will take place on the next release, scheduled at some point in May. Without realizing that Ansible Galaxy needs version numbers in the Semantic format that excludes the preceding “v”, for example 1.2.1 vs v1.2., we have been using tags with the preceding v. This has caused our galaxy space to not update with our latest releases. 

 The plan going forward we plan to adjust the version number formatting on the first release for each repo in May. Please make note that if you are relying on release tags to keep up with latest versions, the numbering format will change. The cadence of the version numbers will continue and progress through as they have been, however the preceding “v” will be dropped from the tag. 

George

**Comment by treyperrone** [comment]
Thanks @georgenalen for that heads up

**Comment by georgenalen** [comment]
This was resolved a few weeks ago
