### ISSUE TITLE
/etc/sssd/sssd.conf file permission issue

### ISSUE THREAD

**Issue by dpbowen** [ansible-lockdown/RHEL7-STIG#365]
Tasks for RHEL-07-040180, RHEL-07-040190 & RHEL-07-040200 set the /etc/sssd/sssd.conf file permissions to 0644. This is not a supported configuration for sssd and prevents the service from starting with the following error message:

sssd[sssd]: Cannot read config file /etc/sssd/sssd.conf. Please check that the file is accessible only by the owner and owned by root.root

Setting the permissions back to 0600 allows the service to start.

**Comment by uk-bolly** [comment]
Hi @dpbowen 

Thank you for taking the time to raise this issue. I have raised the PR #366 and will hopefully be merged over the next couple of days.

uk-bolly

**Comment by georgenalen** [comment]
Addressed in PR #366
