### ISSUE TITLE
RHEL-07-010492 referencing explicit EFI path

### ISSUE THREAD

**Issue by danbarr** [ansible-lockdown/RHEL7-STIG#385]
**Describe the Issue**
The updated RHEL-07-010492 block in fix-cat2.yml in v1.3.1 explicitly references /boot/efi/EFI/redhat/grub.cfg, which will fail on CentOS systems.

**Expected Behavior**
Task should succeed on CentOS.

**Actual Behavior**
Task fails on CentOS due to nonexistent path/file.

**Control(s) Affected**
RHEL-07-010492

**Environment (please complete the following information):**
 - Ansible Version: 2.9.25
 - Host Python Version: Python 3.6.8
 - Ansible Server Python Version: same
- Host OS: CentOS 7.9 in UEFI mode

**Possible Solution**
Replace:
https://github.com/ansible-lockdown/RHEL7-STIG/blob/2b4a30c637ec4c80890e4b98984cfdf9ba7bac48/tasks/fix-cat2.yml#L893

With:
`path: "{{ rhel7stig_bootloader_path }}/grub.cfg"`

**Comment by uk-bolly** [comment]
Hi Dan

As always thank you for highlighting this issue and supplying a resolution. I have raised a new PR for this today and hope to get this pushed through asap.

many thanks again

uk-bolly

**Comment by uk-bolly** [comment]
Hi @danbarr 

I just noticed i closed this in error a little early before the PR was approved. The fix is now in dev and will be rolled in main hopefully later today.
Please feel free to reopen if i have missed anything.

Many thanks

uk-bolly
