### ISSUE TITLE
No longer on Ansible Galaxy?

### ISSUE THREAD

**Issue by yeroc** [ansible-lockdown/RHEL7-STIG#386]
**Describe the Issue**
I tried to update to the latest version and discovered MindPointGroup.RHEL7-STIG is no longer available on Ansible Galaxy.

**Expected Behavior**
Expected to be able to install via Ansible Galaxy as I have done previously.

**Actual Behavior**
Got an error instead:
```
$ ansible-galaxy install --force -r requirements.yml
- changing role MindPointGroup.RHEL7-STIG from 0.1.7 to 1.3.1
- downloading role 'RHEL7-STIG', owned by MindPointGroup
[WARNING]: - MindPointGroup.RHEL7-STIG was NOT installed successfully: - sorry, MindPointGroup.RHEL7-STIG was not found on https://galaxy.ansible.com/api/.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Environment (please complete the following information):**
 - Ansible Version: 2.9.11
 - Host Python Version: 3.8.5

**Possible Solution**
None?

**Comment by yeroc** [comment]
Hmm... bizarre.  I see the `role_name` set in `meta/main.yml` is now set to `rhel8_stig` as of commit 269adbf.  Is this intentional?  Compatibility is still defined as EL7.  Confusing...

**Comment by yeroc** [comment]
Due to the aforementioned `role_name` change it seems like the role is now published as https://galaxy.ansible.com/mindpointgroup/rhel8_stig...  Seems kinda messed up as the `role_name` suggests this is for RHEL8 rather than RHEL7.

**Comment by uk-bolly** [comment]
hi @yeroc 

Thank you very much for taking the time to highlight this issue and for supplying the resolution. I have raised the PR for this and will put this as a priority to be resolved today.

Many thanks

uk-bolly

**Comment by georgenalen** [comment]
Hello @yeroc 

 This issue should be fixed and updated in Galaxy

George

**Comment by yeroc** [comment]
Thanks so much for the timely resolution @uk-bolly @georgenalen !  One thing that will trip up anyone that has been using the role before.  The name has still changed from `rhel7-stig` to `rhel7_stig`.  So everyone will need to discover this new name and then update all references to the role.  Do you have a way of communicating this name change out to all users?
