### ISSUE TITLE
Examples integrating gross and RHEL7-STIG-Audit

### ISSUE THREAD

**Issue by Michael-Angel-Sec** [ansible-lockdown/RHEL7-STIG#390]
Can the documentation for either this repo or both RHEL7-STIG-Audit be expanded, to include examples?
I'm seeing downloading from github with a proxy fails in ansible but works on the command line.  Also Ansible copying from the git repos from the ansible server also appears to fail.

Can RHEL7-STIG-Audit be run manually to resolve auditing issues?

**Comment by uk-bolly** [comment]
hi @Michael-Angel-Sec 

Thank you very much for your feedback,  I would very much like to discuss this further with you to see where this can be improved based upon different setups that people may have.
I have been working on creating some documentation to enhance what is there. I have therefore uploaded a new branch to help demonstrate this into the rhel7-stig-audit repository that may help called docs. 

re proxy:
I have not added the extra steps for the proxy happy to work with you so this can all be run from the remediation role.

For running goss standalone this is possible although the goss vars will need to be set accordingly for the system accordingly.

If you have any questions if particular and would like to discuss this further please send an email via https://engage.mindpointgroup.com/try-ansible-counselor if you state this issue, I will be able to work with you to improve this.
Alternatively, we are looking to add the community options to the repos so we can discuss this with the wider community in the future.

Thanks again

uk-bolly

**Comment by uk-bolly** [comment]
@Michael-Angel-Sec 

Apologies i didn't get to push the branch up i have now added this.
Please let me know if this helps?

Thanks

uk-bolly

**Comment by uk-bolly** [comment]
Hi @Michael-Angel-Sec 

Hopefully the docs help with things?
I will look to add make these accessible to this and other repos going forward.

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
Closing Issue
