### ISSUE TITLE
A boot kernel parameter is added to /etc/default/grub even if there is not a separate boot partition

### ISSUE THREAD

**Issue by dpbowen** [ansible-lockdown/RHEL7-STIG#391]
**Describe the Issue**
A boot kernel parameter is added to /etc/default/grub even if there is not a separate boot partition

**Expected Behavior**
A boot kernel parameter should not be added unless there is a separate boot partition

**Actual Behavior**
The prelim task in prelim.yml, line 301 sets the variable rhel_07_boot_part even if there is not a separate boot partition. For example on a system where boot exists on / the output of the shell command is '/'. 

Due to the variable being set, the RHEL-07-021350 task on lines 484-503 of fix-cat1.yml is adding the boot parameter.

**Control(s) Affected**
RHEL-07-021350

**Environment (please complete the following information):**
 - Ansible Version: 2.9.25
 - Host Python Version: 3.6.8
 - Ansible Server Python Version: 3.6.8

**Additional Notes**
Including the boot parameter when there is not a separate boot partition causes the FIPS integrity check to fail intermittently when the server is booted.

**Possible Solution**
Add a when condition to the task such as: rhel7stig_boot_part not in ['/', '']

**Comment by danbarr** [comment]
Can confirm, I just discovered this and came here to open the same issue.

The RHEL 8 role handles this correctly. Fix for RHEL 7 role is to modify the "when" condition on the RHEL-07-021350 PATCH task  (line 499 in fix-cat1.yaml) from this:
```
              when:
                  - not ansible_check_mode or
                    rhel7_stig_grub_template is not changed
```

To this:
```
              when:
                  - rhel7stig_boot_part not in ['/', '']
                  - not ansible_check_mode or
                    rhel7_stig_grub_template is not changed
```

**Comment by uk-bolly** [comment]
Hi @dpbowen and @danbarr 


Thank you for taking the time to raise this issue and confirming as well as supplying a fix. We are looking at updating to the latest stig release and we are incorporating this into that release.
Hoping to release this in the next couple of days.

regards

uk-bolly
