### ISSUE TITLE
RHEL-07-010110 setting incorrect lock-delay value

### ISSUE THREAD

**Issue by danbarr** [ansible-lockdown/RHEL7-STIG#400]
**Describe the Issue**
RHEL-07-010110 task is setting the org/gnome/desktop/screensaver `lock-delay` value to `uint32 900`, but per the STIG text (validated with v3r5 and the new v3r6), this should be `uint32 5`.

(The task for idle-delay, RHEL-07-010070, is correct at 900)

**Expected Behavior**
Task RHEL-07-010110 in fix-cat2.yaml should set the dconf value for [org/gnome/desktop/screensaver] lock-delay to `uint32 5`.

**Actual Behavior**
Value is being set to `uint32 900`.

**Control(s) Affected**
RHEL-07-010110

**Possible Solution**
Update:
https://github.com/ansible-lockdown/RHEL7-STIG/blob/19091326a0b24b176bebe877caa19f26d6365e6f/tasks/fix-cat2.yml#L195-L197

to:
```
      content: |
          [org/gnome/desktop/screensaver]
          lock-delay=uint32 5
```

**Comment by uk-bolly** [comment]
hi @danbarr 

Thanks as always for your feedback. I have added the update to the AAP branch which will look to merge before we release the new STIG (which is going through testing and audit alignment).

Regards

uk-bolly
