### ISSUE TITLE
Make auditd process a var

### ISSUE THREAD

**Issue by bordenit** [ansible-lockdown/RHEL7-STIG#412]
**Feature Request or Enhancement**
 - Feature []
 - Enhancement [ x ]

**Summary of Request**
The audit daemon is not always auditd, instead of restarting auditd, or notifying auditd, consider replacing with "{{ audit_daemon_service | default ('auditd') }}". The STIG says, "the audit daemon must be restarted for the changes to take effect." This is not specific to auditd.

**Describe alternatives you've considered**
Manually editing file.

**Suggested Code**
Please provide any code you have in mind to fulfill the request

**Comment by uk-bolly** [comment]
hi @bordenit 

Thank you again for raising this issue. This has now been merged into the devel branch. Aiming to put this into main if all is well in the next couple of weeks.

many thanks again

uk-bolly

**Comment by uk-bolly** [comment]
hi @bordenit 

This is merged into main a couple of weeks ago. I will close this issue, please let me know if this continues to be a problem.

thanks as always

uk-bolly
