### ISSUE TITLE
Capture current password state fails

### ISSUE THREAD

**Issue by Sicnus** [ansible-lockdown/RHEL7-STIG#422]
**Describe the Issue**
While using devel branch trying to run site.yml and it is dying @ line 26 column 10 when trying to find {{ ansible_user }} variable.

**Expected Behavior**
This wasn't expected :)

**Additional Notes**
Please consult MrSteve for further details.  :)

**Comment by uk-bolly** [comment]
This is dying in prelim.
when the audit_log_file is not being used and started with a #.
change required to the grep to capture all status
grep -oP '^(#|)log_file\s*=\s*\K.*?(?=\s*$)' /etc/audit/auditd.conf

**Comment by uk-bolly** [comment]
hi @Sicnus 

I believe this has now been resolved. Please let us know if you are still seeing the problem.

thanks

uk-bolly
