### ISSUE TITLE
/boot/efi error with improperly tagged tasks

### ISSUE THREAD

**Issue by prestonSeaman2** [ansible-lockdown/RHEL7-STIG#446]
**Describe the Issue**
Bug encountered when supplying tags to ansible command.  /boot/efi error 
Happens in the prelim.yml 

**Expected Behavior**
Tasks in the prelim.yml should run without generating /boot/efi errors

**Actual Behavior**
When running with tags a /boot/efi error is generated for some tasks.

**Control(s) Affected**
RHEL-07-021350

**Environment (please complete the following information):**

- branch being used: [e.g. devel]
- Ansible Version: [e.g. 2.10]
- Host Python Version: [e.g. Python 3.7.6]
- Ansible Server Python Version: [e.g. Python 3.7.6]
- Additional Details:

**Additional Notes**
Anything additional goes here

**Possible Solution**
Change tags to -always instad of -cat1, -high -rhel-o7-021350

**Comment by georgenalen** [comment]
Merged to main on March 6th via PR #456
