### ISSUE TITLE
Controls associated with the auditd.rules are failing because -F perm=x is not added

### ISSUE THREAD

**Issue by prestonSeaman2** [ansible-lockdown/RHEL7-STIG#452]
**Describe the Issue**
The affected controls are failing now because they added -F perm=x back into the security requirements for the RHEL 7 STIG
Looks like they were removed in 2018 and have recently been added back.

**Expected Behavior**
In the affected controls -F perm=x should be set

**Actual Behavior**
In the affected controls -F perm=x is not being set. 

**Control(s) Affected**
RHEL-07-030560
RHEL-07-030570
RHEL-07-030580
RHEL-07-030590
RHEL-07-030630
RHEL-07-030640
RHEL-07-030650
RHEL-07-030660
RHEL-07-030670
RHEL-07-030680
RHEL-07-030690
RHEL-07-030710
RHEL-07-030720
RHEL-07-030740
RHEL-07-030750
RHEL-07-030760
RHEL-07-030770
RHEL-07-030780
RHEL-07-030800
RHEL-07-030810

**Possible Solution**
-F perm=x should be added to the 99_auditd.rules.j2 file at each control listed above.

**Comment by uk-bolly** [comment]
hi @prestonSeaman2 

I believe this has now been merged, if you are happy the issues has been addressed we can close this issue?

Many thanks

uk-bolly
