### ISSUE TITLE
RHEL-07-020600 prelim.yml should parse /etc/passwd unconditionally

### ISSUE THREAD

**Issue by prestonSeaman2** [ansible-lockdown/RHEL7-STIG#463]
**Describe the Issue**
The prelim.yml should parse /etc/passwd unconditionally.  Currently it does not always run which causes issues further down the script.

**Control(s) Affected**
RHEL-07-020600

**Possible Solution**
Set the tag to -always in prelim.yml at RHEL-07-020600

**Comment by uk-bolly** [comment]
hi @prestonSeaman2 

Thank you again for this issue. The fix has been applied and is now in the main branch and release. I will close this issue, Please reopen if you feel this is not resolved.

Many thanks

uk-bolly
